let
    Source = Excel.CurrentWorkbook(){[Name="COAApi"]}[Content],
    Buffer = Table.Buffer(Source),
    Fuente = Table.SelectColumns(Buffer,{"Cµdigo", "Nombre", "Activo", "Tipo"}),
    Manual = Excel.CurrentWorkbook(){[Name="COALocal"]}[Content],
    ManualTipos = Table.TransformColumnTypes(Manual,{{"Cµdigo", type text}, {"Nombre", type text}}),
    UnirConsultas = Table.NestedJoin(Fuente, {"Cµdigo"}, ManualTipos, {"Cµdigo"}, "ManualTipos", JoinKind.LeftOuter),
    Expandir = Table.ExpandTableColumn(UnirConsultas, "ManualTipos", {"Categoria", "Clasificaciµn"}, {"Categoria", "Clasificaciµn"}),
    CambiarTipos = Table.TransformColumnTypes(Expandir,{{"Categoria", type text},{"Clasificaciµn", type text}}),
    #"Sorted Rows" = Table.Sort(CambiarTipos,{{"Cµdigo", Order.Ascending}})
in
    #"Sorted Rows"
