let
    // 1. Definición de límites basada en parámetros
    #"Merged Queries" = Table.NestedJoin(TrialBalanceApi, {"Código cuenta contable"}, COALocal, {"Código"}, "COALocal", JoinKind.Inner),
    #"Expanded TablePUC" = Table.ExpandTableColumn(#"Merged Queries", "COALocal", {"Clasificación", "Categoria"}, {"Clasificación", "Categoria"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded TablePUC",{{"Clasificación", type text}, {"Categoria", type text}}),
    #"Grouped Rows" = Table.Group(#"Changed Type1", {"Clasificación", "Nombre Cuenta contable", "Categoria", "Nombre tercero", "Fecha inicio"}, {{"MovimientoDebitoCredito", each List.Sum([MovimientoDebitoCredito]), type nullable number}}),
    #"Filtered Rows" = Table.SelectRows(#"Grouped Rows", each [Clasificación] <> null and [Clasificación] <> ""),
    #"Pivoted Column" = Table.Pivot(#"Filtered Rows", List.Distinct(#"Filtered Rows"[Clasificación]), "Clasificación", "MovimientoDebitoCredito", List.Sum),
    #"Renamed Columns" = Table.RenameColumns(#"Pivoted Column",{{"Fixed", "costs_fixed"}, {"Variable", "costs_variable"}, {"Fecha inicio", "period"}, {"Nombre Cuenta contable", "account_name"}, {"Categoria", "category"}, {"Nombre tercero", "thirdparty_name"}})
in
    #"Renamed Columns"
