let
    fnGoogleAdsOperationByPeriod = (Agrupacion as text) as table =>
    let
        // 1. CONFIGURACIÓN Y NORMALIZACIÓN
        AgrupacionNorm = Text.Lower(Text.Trim(Agrupacion)),
        
        // 2. LÓGICA DE FECHAS
        FechaFinGlobal = Date.From(ParamFechaFinReporte),
        FechaIniGlobal = Date.From(ParamFechaInicioReporte),
        HaceUnAño = Date.AddYears(FechaFinGlobal, -1),
        
        FechaDesde = if AgrupacionNorm = "day" 
                     then HaceUnAño 
                     else FechaIniGlobal,
        FechaHasta = FechaFinGlobal,

        // 3. EXTRACCIÓN Y LIMPIEZA INICIAL
        RawData = Csv.Document(Web.Contents(ParamGoogleReportSource),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
        HeaderSkip = Table.Skip(RawData, 4),
        PromotedHeaders = Table.PromoteHeaders(HeaderSkip, [PromoteAllScalars=true]),
        SelectedColumns = Table.SelectColumns(PromotedHeaders, {"Date", "Cost", "Impressions", "Clicks"}),
        FilteredZero = Table.SelectRows(SelectedColumns, each ([Cost] <> "0.00")),
        
        // 4. PARSEO DE TIPOS (Cultura US para Google Ads)
        ValidatedTypes = Table.TransformColumns(FilteredZero, {
            {"Date", each Date.From(DateTime.From(_, "en-US")), type date},
            {"Cost", each Number.From(_, "en-US"), type number},
            {"Impressions", each Int64.From(_), Int64.Type},
            {"Clicks", each Int64.From(_), Int64.Type}
        }),

        // 5. FILTRO DE RANGO
        DataInRange = Table.SelectRows(ValidatedTypes, each [Date] >= FechaDesde and [Date] <= FechaHasta),

        // 6. TRANSFORMACIÓN SEGÚN AGRUPACIÓN
        FinalResult = if AgrupacionNorm = "day" then
                let
                    RenamedDay = Table.RenameColumns(DataInRange, {{"Date", "day"}}),
                    AddedRefreshDay = Table.AddColumn(RenamedDay, "refresh_date", each DateTime.LocalNow(), type datetime)
                in AddedRefreshDay
            else
                let
                    // PASO CLAVE: Normalizamos al primer día del mes para poder agrupar por fechas reales
                    ToStartOfMonth = Table.TransformColumns(DataInRange, {{"Date", each Date.StartOfMonth(_), type date}}),
                    RenamedMonth = Table.RenameColumns(ToStartOfMonth, {{"Date", "month"}}),
                    
                    // Agrupación por la fecha del primer día
                    GroupedByMonth = Table.Group(RenamedMonth, {"month"}, {
                        {"Cost", each List.Sum([Cost]), type number},
                        {"Impressions", each List.Sum([Impressions]), Int64.Type},
                        {"Clicks", each List.Sum([Clicks]), Int64.Type}
                    }),
                    
                    // Aseguramos que la columna 'month' sea explícitamente tipo fecha
                    ValidatedMonthType = Table.TransformColumnTypes(GroupedByMonth, {{"month", type date}}),
                    AddedRefreshMonth = Table.AddColumn(ValidatedMonthType, "refresh_date", each DateTime.LocalNow(), type datetime)
                in AddedRefreshMonth
    in
        FinalResult,

    // 7. DOCUMENTACIÓN
    TypeFunction = type function (
        Agrupacion as (type text meta [
            Documentation.Name = "fnGoogleAdsOperationByPeriod",
            Documentation.LongDescription = "Extrae datos de Google Ads. Si es 'month', agrupa los valores en el primer día de cada mes con formato de fecha.",
            Documentation.AllowedValues = {"day", "month"}
        ])
    ) as table
in
    Value.ReplaceType(fnGoogleAdsOperationByPeriod, TypeFunction)
