let
    fnMetaAdsOperationByPeriod = (
        Agrupacion as text
    ) as table =>
    let
        // 1. ConfiguraciÛn de Par·metros y NormalizaciÛn
        AgrupacionNorm = Text.Lower(Text.Trim(Agrupacion)),
        Token          = ParamMetaSystemToken,
        AdAccountId    = ParamMetaAccountID,
        
        // 2. LÛgica de Fechas
        FechaFinGlobal = Date.From(ParamFechaFinReporte),
        FechaIniGlobal = Date.From(ParamFechaInicioReporte),
        HaceUnAÒo      = Date.AddYears(FechaFinGlobal, -1),
        
        FechaDesde = if AgrupacionNorm = "day" 
                     then List.Max({HaceUnAÒo, FechaIniGlobal}) 
                     else FechaIniGlobal,
        FechaHasta = FechaFinGlobal,

        // 3. PaginaciÛn Recursiva
        GetPages = (URL as text) as list =>
            let
                Source = Json.Document(Web.Contents(URL)),
                Data   = try Source[data] otherwise {},
                Next   = try Source[paging][next] otherwise null,
                Result = if Next <> null 
                         then List.Combine({Data, @GetPages(Next)}) 
                         else Data
            in
                Result,

        // 4. Llamada (Mantenemos incremento diario para m·xima precisiÛn)
        GetChunk = (ChunkDesde as date, ChunkHasta as date) as list =>
            GetPages(
                "https://graph.facebook.com/v19.0/"
                & AdAccountId & "/insights"
                & "?fields=date_start,campaign_name,spend,clicks,impressions"
                & "&level=campaign"
                & "&time_increment=1" // Mantenemos 1 para sumar nosotros
                & "&time_range={'since':'" & Date.ToText(ChunkDesde, "yyyy-MM-dd") 
                & "','until':'" & Date.ToText(ChunkHasta, "yyyy-MM-dd") & "'}"
                & "&limit=500"
                & "&access_token=" & Token
            ),

        // 5. GeneraciÛn de Chunks
        TotalYears  = Date.Year(FechaHasta) - Date.Year(FechaDesde) + 1,
        YearChunks  = List.Generate(
                          () => 0,
                          each _ < TotalYears,
                          each _ + 1,
                          each let
                               ChunkStart = Date.AddYears(#date(Date.Year(FechaDesde), 1, 1), _),
                               ChunkEnd   = Date.AddYears(#date(Date.Year(FechaDesde), 12, 31), _),
                               ActualStart = if ChunkStart < FechaDesde then FechaDesde else ChunkStart,
                               ActualEnd   = if ChunkEnd > FechaHasta then FechaHasta else ChunkEnd
                          in {ActualStart, ActualEnd}
                      ),

        // 6. RecopilaciÛn
        AllData = List.Combine(List.Transform(YearChunks, each GetChunk(_{0}, _{1}))),

        // 7. Estructura Base
        BaseTable = if List.IsEmpty(AllData) then
                #table(type table [date_start=text, campaign_name=text, spend=number, clicks=Int64.Type, impressions=Int64.Type], {})
            else
                let
                    FromList = Table.FromList(AllData, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
                    Expanded = Table.ExpandRecordColumn(FromList, "Column1", {"date_start", "campaign_name", "spend", "clicks", "impressions"}),
                    Typed    = Table.TransformColumnTypes(Expanded, {
                                    {"date_start", type date}, {"campaign_name", type text}, {"spend", type number}, 
                                    {"clicks", Int64.Type}, {"impressions", Int64.Type}})
                in Typed,

        // 8. TransformaciÛn seg˙n AgrupaciÛn
        Result = if AgrupacionNorm = "day" then
                let
                    DayRenamed = Table.RenameColumns(BaseTable, {{"date_start", "day"}}),
                    DayFinal   = Table.AddColumn(DayRenamed, "refresh_date", each DateTime.LocalNow(), type datetime)
                in DayFinal
            else
                let
                    // Convertimos cada fecha al inicio de su mes (ej: 2024-05-15 -> 2024-05-01)
                    ToMonthStart = Table.TransformColumns(BaseTable, {{"date_start", each Date.StartOfMonth(_), type date}}),
                    MonthRenamed = Table.RenameColumns(ToMonthStart, {{"date_start", "month"}}),
                    // Agrupamos para sumar los valores diarios en un ˙nico registro mensual
                    Grouped      = Table.Group(MonthRenamed, {"month", "campaign_name"}, {
                                    {"spend", each List.Sum([spend]), type number},
                                    {"clicks", each List.Sum([clicks]), Int64.Type},
                                    {"impressions", each List.Sum([impressions]), Int64.Type}}),
                    MonthFinal   = Table.AddColumn(Grouped, "refresh_date", each DateTime.LocalNow(), type datetime)
                in MonthFinal
    in
        Result,

    fnType = type function (
        Agrupacion as (type text meta [
            Documentation.FieldCaption  = "AgrupaciÛn",
            Documentation.AllowedValues    = {"day", "month"}
        ])
    ) as table
in
    Value.ReplaceType(fnMetaAdsOperationByPeriod, fnType)
