let
    FuncLogic = (
        GroupByFieldInput as text, 
        FechaInicio as date, 
        FechaFin as date, 
        FechaRefresco as date, 
        optional NombreTablaHistorica as text
    ) as table =>
    let
        SourceTable = "sales",
        ColumnsToShow = "total_sales",
        WhereFilter = "order_utm_campaign IS NOT NULL",
        ShopifyGroup = GroupByFieldInput & ", order_utm_campaign, order_referrer_source, order_utm_source",

        Periods = fnGetDatesInPeriod(FechaInicio, FechaFin, FechaRefresco, GroupByFieldInput, ParamDiaSemanaReporte, NombreTablaHistorica),

        PreparedQueries = Table.AddColumn(Periods, "CustomQuery", each 
            "FROM " & SourceTable & " " & 
            "SHOW " & ColumnsToShow & " " & 
            "GROUP BY " & ShopifyGroup & " " & 
            "WHERE " & WhereFilter & " " & 
            "SINCE " & Date.ToText([startDate], "yyyy-MM-dd") & " " & 
            "UNTIL " & Date.ToText([endDate], "yyyy-MM-dd")
        , type text),

        InvokeAPI = Table.AddColumn(PreparedQueries, "Data", each try fnGetShopifyQLData([CustomQuery]) otherwise null),

        ValidData = Table.SelectRows(InvokeAPI, each 
            let 
                val = [Data],
                isNotVoid = val <> null and not (val is text and val = "")
            in 
                try isNotVoid otherwise false
        ),

        // --- MEJORA 1: EXPANSIÓN DINÁMICA REAL ---
        ExpandedResults = if Table.IsEmpty(ValidData) then 
            #table({GroupByFieldInput, "order_utm_campaign", "order_referrer_source", "order_utm_source", "total_sales"}, {})
        else 
            let
                ListExp = Table.ExpandListColumn(ValidData, "Data"),
                // Detectamos TODAS las columnas presentes en los registros devueltos
                AllColumnNames = List.Distinct(List.Combine(List.Transform(ListExp[Data], each Record.FieldNames(_)))),
                Exp = Table.ExpandRecordColumn(ListExp, "Data", AllColumnNames)
            in
                Exp,

        CleanSalesStep = Table.TransformColumns(ExpandedResults, {
            {"total_sales", each if _ = null or _ = "" then 0 else Number.From(_, "en-US"), type number}
        }),

        CleanNulls = Table.ReplaceValue(CleanSalesStep, null, "sin identificar", Replacer.ReplaceValue, {GroupByFieldInput, "order_utm_campaign", "order_referrer_source", "order_utm_source"}),

        TransformPeriod = Table.TransformColumns(CleanNulls, {
            {GroupByFieldInput, each 
                let 
                    txt = Text.From(_),
                    isYearMonth = Text.Length(txt) <= 7 and Text.Contains(txt, "-") and txt <> "sin identificar",
                    res = if GroupByFieldInput = "month" and isYearMonth then txt & "-01" else txt
                in res, 
            type text}
        }),

        FixInvalidDates = Table.ReplaceValue(TransformPeriod, "sin identificar", null, Replacer.ReplaceValue, {GroupByFieldInput}),
        
        FinalPeriodStep = Table.TransformColumnTypes(FixInvalidDates, { 
            {GroupByFieldInput, type date},
            {"order_utm_campaign", type text},
            {"order_referrer_source", type text},
            {"order_utm_source", type text}
        }),

        // --- MEJORA 2: LIMPIEZA DE FUENTES ANTES DEL PIVOT ---
        // Esto evita tener "Facebook", "facebook" y "FACEBOOK" como columnas separadas
        StandardizedSources = Table.TransformColumns(FinalPeriodStep, {
            {"order_utm_source", each Text.Lower(Text.Trim(Text.From(_))), type text}
        }),

        PivotedColumns = if Table.IsEmpty(StandardizedSources) then StandardizedSources else 
            let
                RawNames = List.Distinct(StandardizedSources[order_utm_source]),
                CleanNames = List.Select(RawNames, each _ <> null and _ <> "" and _ <> "sin identificar")
            in
                Table.Pivot(StandardizedSources, CleanNames, "order_utm_source", "total_sales", List.Sum),

        // --- SUMA DINÁMICA ---
        TechnicalCols = {GroupByFieldInput, "order_utm_campaign", "order_referrer_source", "startDate", "endDate", "CustomQuery", "Data", "refresh_date", "Total_Sales_Combined", "refresh_date_SalesByUTM"},
        ExistingCols = Table.ColumnNames(PivotedColumns),
        MetricsToSum = List.Select(ExistingCols, each not List.Contains(TechnicalCols, _)),
        
        AddTotal = Table.AddColumn(PivotedColumns, "Total_Sales_Combined", each 
            let 
                currentRecord = _,
                valuesList = Record.ToList(Record.SelectFields(currentRecord, MetricsToSum)),
                cleanValues = List.Select(valuesList, each _ is number)
            in 
                List.Sum(cleanValues), type number),

        UpdateColumn = Table.AddColumn(AddTotal, "refresh_date_SalesByUTM", each DateTime.LocalNow(), type datetime),
        
        // --- TIPADO FINAL ---
        MetricTypeTransform = List.Transform(MetricsToSum, each {_, type number}),
        BaseTypeTransform = {
            {GroupByFieldInput, type date},
            {"order_utm_campaign", type text},
            {"order_referrer_source", type text},
            {"Total_Sales_Combined", type number},
            {"refresh_date_SalesByUTM", type datetime}
        },
        
        FullTypeTransform = List.Combine({BaseTypeTransform, MetricTypeTransform}),
        TargetCols = List.Combine({{GroupByFieldInput, "order_utm_campaign", "order_referrer_source", "Total_Sales_Combined", "refresh_date_SalesByUTM"}, MetricsToSum}),
        FinalExistingCols = List.Select(TargetCols, each List.Contains(Table.ColumnNames(UpdateColumn), _)),
        
        RemovedSystemCols = Table.SelectColumns(UpdateColumn, FinalExistingCols),
        FinalTableTyped = Table.TransformColumnTypes(RemovedSystemCols, List.Select(FullTypeTransform, each List.Contains(Table.ColumnNames(RemovedSystemCols), _{0})))
    in
        Table.Sort(FinalTableTyped, {{GroupByFieldInput, Order.Ascending}}),

    TypeFunction = type function (
        GroupByFieldInput as (type text meta [
            Documentation.FieldCaption = "Nivel de Agrupación",
            Documentation.AllowedValues = {"day", "month"}
        ]),
        FechaInicio as (type date),
        FechaFin as (type date),
        FechaRefresco as (type date),
        optional NombreTablaHistorica as (type text)
    ) as table meta [
        Documentation.Name = "fnSalesByUTMByPeriod",
        Documentation.LongDescription = "Consulta de ventas por UTM con estandarización de fuentes y expansión dinámica."
    ]
in
    Value.ReplaceType(FuncLogic, TypeFunction)
