let
    // 1. DEFINICIÓN DE METADATOS PARA EL PANEL (Ajustado a date)
    TypeFunction = type function (
        GroupByField as (type text meta [
            Documentation.FieldCaption = "Nivel de Agrupación",
            Documentation.AllowedValues = {"day", "week", "month"}
        ]),
        FechaInicio as (type date meta [Documentation.FieldCaption = "Fecha Inicial"]),
        FechaFin as (type date meta [Documentation.FieldCaption = "Fecha Final"]),
        FechaRefresco as (type date meta [Documentation.FieldCaption = "Fecha Refrescar Histórico"]),
        optional NombreTablaHistorica as (type text meta [Documentation.FieldCaption = "Nombre Tabla Excel (Opcional)"])
    ) as table meta [
        Documentation.Name = "fnGetSalesDetailedByPeriod",
        Documentation.LongDescription = "Consulta detallada de ventas (producto, origen, cliente) compatible con la lógica de periodos y consolidación local."
    ],

    // 2. LÓGICA INTERNA
    FuncLogic = (
        GroupByField as text, 
        FechaInicio as date, 
        FechaFin as date, 
        FechaRefresco as date, 
        optional NombreTablaHistorica as text
    ) as table =>
    let
        SourceTable = "sales",
        ColumnsToShow = "quantity_ordered, net_sales",
        MetafieldColumn = "order.metafields.custom.origen_venta",
        
        // RESTRICCIÓN: Si es week, pedimos 'day' para agrupar localmente
        ApiTimeGroup = if GroupByField = "week" then "day" else GroupByField,
        FullGroupBy = ApiTimeGroup & ", " & MetafieldColumn & ", product_title, new_or_returning_customer",

        // Obtención de periodos (Ya vienen como date)
        Periods = fnGetDatesInPeriod(FechaInicio, FechaFin, FechaRefresco, GroupByField, ParamDiaSemanaReporte, NombreTablaHistorica),

        // Construcción de consultas ShopifyQL
        PreparedQueries = Table.AddColumn(Periods, "CustomQuery", each 
            "FROM " & SourceTable & " " &
            "SHOW " & ColumnsToShow & " " &
            "GROUP BY " & FullGroupBy & " " & 
            "SINCE " & Date.ToText([startDate], "yyyy-MM-dd") & " " & 
            "UNTIL " & Date.ToText([endDate], "yyyy-MM-dd") & " " &
            "ORDER BY quantity_ordered DESC"
        , type text),

        // Invocación API con manejo de errores
        InvokeAPI = Table.AddColumn(PreparedQueries, "Data", each try fnGetShopifyQLData([CustomQuery]) otherwise null),
        ValidData = Table.SelectRows(InvokeAPI, each [Data] <> null and [Data] <> ""),

        ResultTable = if Table.IsEmpty(ValidData) then 
            #table({GroupByField, "source", "product_title", "new_or_returning_customer", "quantity_ordered", "net_sales"}, {})
        else
            let
                // 3. EXPANSIÓN DINÁMICA PROTEGIDA
                ExpandedList = Table.ExpandListColumn(ValidData, "Data"),
                
                // Obtener nombres de columnas reales devueltos por la API (con prefijo api_)
                SampleRecord = List.First(ExpandedList[Data]),
                FieldsInRecord = Record.FieldNames(SampleRecord),
                ExpandedRecords = Table.ExpandRecordColumn(ExpandedList, "Data", FieldsInRecord, List.Transform(FieldsInRecord, each "api_" & _)),
                
                // Normalización de nombres de columnas técnicas de Shopify
                TargetApiDateCol = "api_" & ApiTimeGroup,
                TargetApiSourceCol = "api_" & MetafieldColumn,

                // 4. LIMPIEZA DE DIMENSIONES (Metafields y Nulos)
                CleanMetafields = Table.TransformColumns(ExpandedRecords, {
                    {TargetApiSourceCol, each if _ is list then Text.Combine(List.Transform(_, each Text.From(_)), ", ") else if _ = null then "Online store" else Text.From(_)}
                }),

                // Tipado numérico preventivo para consolidación
                PreTyped = Table.TransformColumnTypes(CleanMetafields, {
                    {"api_quantity_ordered", Int64.Type},
                    {"api_net_sales", type number}
                }),

                // 5. CONSOLIDACIÓN LOCAL SI ES 'WEEK'
                Consolidated = if GroupByField = "week" then
                    Table.Group(PreTyped, {"startDate", TargetApiSourceCol, "api_product_title", "api_new_or_returning_customer"}, {
                        {"quantity_ordered", each List.Sum([api_quantity_ordered]), Int64.Type},
                        {"net_sales", each List.Sum([api_net_sales]), type number}
                    })
                else 
                    // Si no es week, renombramos columnas para estandarizar con la salida de week
                    let 
                        RenamedApi = Table.RenameColumns(PreTyped, {
                            {TargetApiDateCol, GroupByField},
                            {TargetApiSourceCol, "source"},
                            {"api_product_title", "product_title"},
                            {"api_new_or_returning_customer", "new_or_returning_customer"},
                            {"api_quantity_ordered", "quantity_ordered"},
                            {"api_net_sales", "net_sales"}
                        })
                    in RenamedApi,

                // Ajuste de nombres para la rama de 'week'
                FinalRenamed = if GroupByField = "week" then 
                    Table.RenameColumns(Consolidated, {
                        {"startDate", "week"},
                        {TargetApiSourceCol, "source"},
                        {"api_product_title", "product_title"},
                        {"api_new_or_returning_customer", "new_or_returning_customer"}
                    }) else Consolidated,

                // 6. NORMALIZACIÓN DE FECHAS (Especialmente para Meses de ShopifyQL)
                TransformDate = if GroupByField = "month" then 
                                    Table.TransformColumns(FinalRenamed, {{GroupByField, each if Text.Length(Text.From(_)) = 7 then Date.FromText(Text.From(_) & "-01") else Date.From(_), type date}})
                                 else FinalRenamed,

                // Filtro final de columnas
                FinalColumns = Table.SelectColumns(TransformDate, {GroupByField, "source", "product_title", "new_or_returning_customer", "quantity_ordered", "net_sales"})
            in
                FinalColumns,

        // 7. ASIGNACIÓN DE TIPOS FINALES Y LIMPIEZA
        AllColumns = Table.ColumnNames(ResultTable),
        TypedTable = List.Accumulate(AllColumns, ResultTable, (state, current) =>
            if current = GroupByField then Table.TransformColumnTypes(state, {{current, type date}})
            else if current = "quantity_ordered" then Table.TransformColumnTypes(state, {{current, Int64.Type}})
            else if current = "net_sales" then Table.TransformColumnTypes(state, {{current, type number}})
            else Table.TransformColumnTypes(state, {{current, type text}})
        ),

        AddedRefreshDate = Table.AddColumn(TypedTable, "refresh_date_SalesQSort", each DateTime.LocalNow(), type datetime),
        
        // Ordenar resultados para reporte
        Final = Table.Sort(AddedRefreshDate, {{GroupByField, Order.Ascending}, {"net_sales", Order.Descending}})
    in
        Final
in
    Value.ReplaceType(FuncLogic, TypeFunction)
