let
    // 1. CONFIGURATION (Replace with your actual credentials)
    ShopifyStoreName = ParamShopName, // e.g., "my-awesome-shop" (do not include .myshopify.com)
    ApiVersion = "2026-04",               // Use your desired stable API version
    AccessToken = ParamAccessToken, // Your Admin API Access Token

    // 2. ENDPOINT & GRAPHQL QUERY PREPARATION
    Url = "https://" & ShopifyStoreName & ".myshopify.com/admin/api/" & ApiVersion & "/graphql.json",
    
    GraphQLQuery = "{
      metafieldDefinitions(ownerType: ORDER, first: 20) {
        edges {
          node {
            namespace
            key
            capabilities { analyticsQueryable { enabled } }
          }
        }
      }
    }",

    // Format the payload as a JSON object containing the "query" property
    Payload = Json.FromValue([query = GraphQLQuery]),

    // 3. HTTP POST REQUEST
    Source = Web.Contents(
        Url,
        [
            Headers = [
                #"X-Shopify-Access-Token" = AccessToken,
                #"Content-Type" = "application/json"
            ],
            Content = Payload
        ]
    ),

    // 4. PARSING AND DRILLING DOWN INTO THE RESULT
    JsonResponse = Json.Document(Source),
    data = JsonResponse[data],
    metafieldDefinitions = data[metafieldDefinitions],
    edges = metafieldDefinitions[edges],
    
    // Convert the list of edges into a structured table
    TableFromList = Table.FromList(edges, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(TableFromList, "Column1", {"node"}, {"node"}),
    
    // Final Expansion of the Metafield attributes
    #"Expanded node" = Table.ExpandRecordColumn(#"Expanded Column1", "node", {"namespace", "key", "capabilities"}, {"namespace", "key", "capabilities"}),
    #"Expanded capabilities" = Table.ExpandRecordColumn(#"Expanded node", "capabilities", {"analyticsQueryable"}, {"analyticsQueryable"}),
    #"Expanded analyticsQueryable" = Table.ExpandRecordColumn(#"Expanded capabilities", "analyticsQueryable", {"enabled"}, {"analyticsQueryable.enabled"})
in
    #"Expanded analyticsQueryable"
