let
    // 1. CARGA DE ORIGEN PRINCIPAL
    RawData = SalesBreakdownMonthly,

    // --- PREPARACIÆN DE COLUMNAS DINêMICAS ---
    // Detectamos las columnas de las tablas mensuales, excluyendo "month"
    ColsSalesBySource = List.RemoveItems(Table.ColumnNames(SalesBySourceToColsMonthly), {"month"}),
    ColsConversionRate = List.RemoveItems(Table.ColumnNames(ConversionRateToColsMonthly), {"month"}),

    // 2. UNIÆN CON VENTAS NUEVOS VS RECURRENTES (Campos fijos)
    JoinNewReturning = Table.NestedJoin(RawData, {"month"}, SalesNewReturningMonthly, {"month"}, "SalesNewReturning", JoinKind.LeftOuter),
    ExpandNewReturning = Table.ExpandTableColumn(JoinNewReturning, "SalesNewReturning", 
        {"returning_customers", "returning_orders", "returning_net_sales", "returning_average_order_value", "returning_cost_of_goods_sold", "returning_gross_profit", "new_customers", "new_orders", "new_net_sales", "new_average_order_value", "new_cost_of_goods_sold", "new_gross_profit", "unknown_customers", "unknown_orders", "unknown_net_sales", "unknown_average_order_value", "unknown_cost_of_goods_sold", "unknown_gross_profit"}),

    // 3. UNIÆN CON VENTAS POR FUENTE (CANALES DINêMICOS)
    JoinSalesBySource = Table.NestedJoin(ExpandNewReturning, {"month"}, SalesBySourceToColsMonthly, {"month"}, "SalesBySourceToCols", JoinKind.LeftOuter),
    ExpandSalesBySource = Table.ExpandTableColumn(JoinSalesBySource, "SalesBySourceToCols", ColsSalesBySource, ColsSalesBySource),

    // 4. UNIÆN CON TASA DE CONVERSIÆN POR REFERIDO (REFERIDOS DINêMICOS)
    JoinConversionRate = Table.NestedJoin(ExpandSalesBySource, {"month"}, ConversionRateToColsMonthly, {"month"}, "ConversionRateByReferral", JoinKind.LeftOuter),
    ExpandConversionRate = Table.ExpandTableColumn(JoinConversionRate, "ConversionRateByReferral", ColsConversionRate, ColsConversionRate),

    // 5. UNIÆN CON GOOGLE ADS
    JoinGoogleAds = Table.NestedJoin(ExpandConversionRate, {"month"}, GoogleAdsOperationMonthly, {"month"}, "GoogleAdsOperation", JoinKind.LeftOuter),
    ExpandGoogleAds = Table.ExpandTableColumn(JoinGoogleAds, "GoogleAdsOperation", {"Cost", "Impressions", "Clicks"}, {"GoogleAdsOperation.Cost", "GoogleAdsOperation.Impressions", "GoogleAdsOperation.Clicks"}),

    // 6. UNIÆN CON META ADS
    JoinMetaAds = Table.NestedJoin(ExpandGoogleAds, {"month"}, MetaAdsOperationMonthly, {"month"}, "MetaAdsOperation", JoinKind.LeftOuter),
    AggregateMetaAds = Table.AggregateTableColumn(JoinMetaAds, "MetaAdsOperation", {
        {"spend", List.Sum, "MetaAdsOperation.spend"}, 
        {"clicks", List.Sum, "MetaAdsOperation.clicks"}, 
        {"impressions", List.Sum, "MetaAdsOperation.impressions"}
    }),

    // 7. ASIGNACIÆN DE TIPOS FINALES
    ValidatedTypes = Table.TransformColumnTypes(AggregateMetaAds,{
        {"MetaAdsOperation.spend", type number}, 
        {"MetaAdsOperation.clicks", Int64.Type}, 
        {"MetaAdsOperation.impressions", Int64.Type}
    })
in
    ValidatedTypes
