let
    Source = Excel.CurrentWorkbook(){[Name="SummaryMonthlyData"]}[Content],
    ChangeTypeDate = Table.TransformColumnTypes(Source,{{"month", type date}}),
    FilterRowsRefresh = Table.SelectRows(ChangeTypeDate, each [month] <= Date.From(ParamFechaRefrescarHistorico)),
    ChangedType = Table.TransformColumnTypes(FilterRowsRefresh,{{"month", type date}, {"orders", Int64.Type}, {"quantity_ordered_per_order", type number}, {"average_order_value", type number}, {"quantity_returned", Int64.Type}, {"gross_sales", type number}, {"discounts", type number}, {"sales_reversals", type number}, {"net_sales", type number}, {"shipping_charges", Int64.Type}, {"return_fees", Int64.Type}, {"taxes", type number}, {"total_sales", Int64.Type}, {"net_sales_without_cost_recorded", type number}, {"net_sales_with_cost_recorded", type number}, {"cost_of_goods_sold", Int64.Type}, {"gross_profit", type number}, {"gift_card_gross_sales", Int64.Type}, {"net_items_sold", Int64.Type}, {"gift_card_discounts", Int64.Type}, {"gift_card_net_sales", Int64.Type}, {"returning_customers", Int64.Type}, {"returning_orders", Int64.Type}, {"returning_net_sales", type number}, {"returning_average_order_value", type number}, {"returning_cost_of_goods_sold", Int64.Type}, {"returning_gross_profit", type number}, {"new_customers", Int64.Type}, {"new_orders", Int64.Type}, {"new_net_sales", type number}, {"new_average_order_value", type number}, {"new_cost_of_goods_sold", Int64.Type}, {"new_gross_profit", type number}, {"unknown_customers", Int64.Type}, {"unknown_orders", Int64.Type}, {"unknown_net_sales", type number}, {"unknown_average_order_value", type number}, {"unknown_cost_of_goods_sold", Int64.Type}, {"unknown_gross_profit", type number}, {"Rappi_net_sales", type number}, {"Rappi_orders", Int64.Type}, {"Rappi_average_order_value", type number}, {"Rappi_cost_of_goods_sold", Int64.Type}, {"Online Store_net_sales", type number}, {"Online Store_orders", Int64.Type}, {"Online Store_average_order_value", type number}, {"Online Store_cost_of_goods_sold", Int64.Type}, {"Tienda 81_net_sales", type number}, {"Tienda 81_orders", Int64.Type}, {"Tienda 81_average_order_value", type number}, {"Tienda 81_cost_of_goods_sold", Int64.Type}, {"Corporativo no tienda_net_sales", type number}, {"Corporativo no tienda_orders", Int64.Type}, {"Corporativo no tienda_average_order_value", type number}, {"Corporativo no tienda_cost_of_goods_sold", Int64.Type}, {"Feria_net_sales", type number}, {"Feria_orders", Int64.Type}, {"Feria_average_order_value", type number}, {"Feria_cost_of_goods_sold", Int64.Type}, {"unknown_sessions", Int64.Type}, {"unknown_sessions_that_completed_checkout", Int64.Type}, {"unknown_conversion_rate", type number}, {"social_sessions", Int64.Type}, {"social_sessions_that_completed_checkout", Int64.Type}, {"social_conversion_rate", type number}, {"search_sessions", Int64.Type}, {"search_sessions_that_completed_checkout", Int64.Type}, {"search_conversion_rate", type number}, {"paid_sessions", Int64.Type}, {"paid_sessions_that_completed_checkout", Int64.Type}, {"paid_conversion_rate", Int64.Type}, {"direct_sessions", Int64.Type}, {"direct_sessions_that_completed_checkout", Int64.Type}, {"direct_conversion_rate", type number}, {"Total site_sessions", Int64.Type}, {"Total site_sessions_that_completed_checkout", Int64.Type}, {"Total site_conversion_rate", type number}, {"email_sessions", Int64.Type}, {"email_sessions_that_completed_checkout", Int64.Type}, {"email_conversion_rate", Int64.Type}, {"GoogleAdsOperation.Cost", type number}, {"GoogleAdsOperation.Impressions", Int64.Type}, {"GoogleAdsOperation.Clicks", Int64.Type}, {"MetaAdsOperation.spend", Int64.Type}, {"MetaAdsOperation.clicks", Int64.Type}, {"MetaAdsOperation.impressions", Int64.Type}}),
    AppendedQuery = Table.Combine({ChangedType, SummaryMonthly})
in
    AppendedQuery
